# Generated by Django 5.1.7 on 2025-03-15 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0012_alter_subcounty_name'),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedDistri',
            fields=[
                ('issued_on', models.DateTimeField(auto_now_add=True)),
                ('farmer_id', models.AutoField(primary_key=True, serialize=False)),
                ('farmer_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=15, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('county', models.CharField(choices=[('Kitui', 'Kitui'), ('Makueni', 'Makueni')], max_length=100)),
                ('ward', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('acres', models.DecimalField(decimal_places=2, max_digits=5)),
                ('seed_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('variety', models.CharField(max_length=50)),
                ('farmer_recruited', models.ForeignKey(blank=True, db_column='farmer_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seed_data', to='recruitment.fielddata')),
                ('field_officer', models.ForeignKey(limit_choices_to={'role': 'field_officer'}, on_delete=django.db.models.deletion.CASCADE, related_name='seed_distribution_fielddata', to='authentication.userprofile')),
                ('sub_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.subcounty')),
            ],
        ),
    ]
