# Generated by Django 5.1.7 on 2025-03-15 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0012_alter_subcounty_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('purchases_on', models.DateTimeField(auto_now_add=True)),
                ('farmer_id', models.AutoField(primary_key=True, serialize=False)),
                ('farmer_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=15, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('county', models.CharField(choices=[('Kitui', 'Kitui'), ('Makueni', 'Makueni')], max_length=100)),
                ('ward', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('clean_castor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('husk_castor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('threshed_castor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('field_officer', models.ForeignKey(limit_choices_to={'role': 'field_officer'}, on_delete=django.db.models.deletion.CASCADE, related_name='purchases_fielddata', to='authentication.userprofile')),
                ('sub_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_data', to='authentication.subcounty')),
            ],
        ),
    ]
