# Generated by Django 5.1.7 on 2025-03-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_region_fielddata_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sub_county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='FieldData',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
