# Generated by Django 5.1.7 on 2025-03-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_region_supervisor_userprofile_sub_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sub_county2',
            field=models.CharField(blank=True, choices=[('kitui_east', 'Kitui East'), ('kitui_west', 'Kitui West'), ('kitui_rural', 'Kitui Rural'), ('mwingi_north', 'Mwingi North'), ('mwingi_central', 'Mwingi Central'), ('mbooni_west', 'Mbooni West')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sub_county',
            field=models.CharField(blank=True, choices=[('kitui_east', 'Kitui East'), ('kitui_west', 'Kitui West'), ('kitui_rural', 'Kitui Rural'), ('mwingi_north', 'Mwingi North'), ('mwingi_central', 'Mwingi Central'), ('mbooni_west', 'Mbooni West')], max_length=100, null=True),
        ),
    ]
