# Generated by Django 5.1.7 on 2025-03-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userprofile_sub_county2_alter_userprofile_sub_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sub_county2',
        ),
    ]
