# Generated by Django 5.1.7 on 2025-03-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_userprofile_sub_county2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Field Officer', 'Field Officer'), ('Supervisor', 'Supervisor'), ('Project Manager', 'Project Manager')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sub_county',
            field=models.CharField(blank=True, choices=[('Kitui East', 'Kitui East'), ('Kitui West', 'Kitui West'), ('Kitui Rural', 'Kitui Rural'), ('Mwingi North', 'Mwingi North'), ('Mwingi Central', 'Mwingi Central'), ('Mbooni West', 'Mbooni West')], max_length=100, null=True),
        ),
    ]
