# Generated by Django 5.1.7 on 2025-03-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_subcounty_sub_county'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcounty',
            old_name='sub_county',
            new_name='name',
        ),
    ]
