# Generated by Django 5.1.7 on 2025-03-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_rename_sub_county_subcounty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcounty',
            name='name',
            field=models.CharField(choices=[('Kitui East', 'Kitui East'), ('Kitui West', 'Kitui West'), ('Kitui Rural', 'Kitui Rural'), ('Mwingi North', 'Mwingi North'), ('Mwingi Central', 'Mwingi Central'), ('Mbooni West', 'Mbooni West')], max_length=100),
        ),
    ]
