# Generated by Django 5.1.7 on 2025-03-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_subcounty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Field Officer', 'Field Officer'), ('supervisor', 'supervisor'), ('Project Manager', 'Project Manager')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sub_county',
            field=models.ManyToManyField(related_name='supervisor', to='authentication.subcounty'),
        ),
    ]
