# Generated by Django 5.1.7 on 2025-03-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_userprofile_role_alter_userprofile_sub_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcounty',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
